#!/bin/bash
#application="packer"
sudo yum install -y wget unzip
wget -O /tmp/packer.zip https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip
sudo unzip /tmp/packer.zip -d /opt/packer
sudo ln -s /opt/packer/packer /usr/bin/packer.io
